apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - web-external
    - websecure-external
    - web
    - websecure
  containers:
    - args:
        - '--name=whoami'
  routes:
  - match: Host(`whoami.local`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  # For HTTPS test (uncomment when you have certs):
  # tls:
  #   certResolver: cloudflare   # once you enable the resolver above