apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
resources:
- namespace.yaml
- gitlab-pvc.yaml
- gitlab-config.yaml
- gitlab-service.yaml
- gitlab-deployment.yaml
- gitlab-ingressroute.yaml
- gitlab-registry-ingressroute.yaml