config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/TheEndBoss101-Web/k8s-gitops_test.git
      targetRevision: HEAD

applications:
  - name: traefik
    namespace: argocd
    destination:
      namespace: traefik
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 40.2.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/TheEndBoss101-Web/k8s-gitops_test/main/traefik/values.yaml
      values: |
        fullnameOverride: traefik